### ISSUE TITLE
What does "socketFile" mean?

### ISSUE THREAD

**Issue by HolmesZhu** [caprica/juds#2]
Hello, I'd like to consult about the role of socketFile in TestUnixDomainSocket. Java.

**Comment by caprica** [comment]
It's the name of the file in the filesystem that provides access to the underlying domain socket.

For example, the LIRC project (used to interface with infra red remotes) provides a socket via the "/var/run/lirc/lircd" file. That is the name you'd pass as the socketFile parameter.
